### ISSUE TITLE
Lost Admin right 

### ISSUE THREAD

**Issue by natir** [anwiki/anwiki#34]
Hello,

I install anwiki, one tuxfamily.org hosting service, anwiki script install is block one check we can write in sessions path, or in can write one this path, i disable  the test.

All install is okay, but when i disconnect and reconnect my admin user lost admin permission and no other user can edit page or anything. 

How i can get admin permission one user ?

**Comment by anwfr** [comment]
Hi,

Thanks for your feedback, and sorry for the delay !

Admin users are stored in this file:
php-include/anwiki-src/_override/drivers/aclsdrivers/aclsdriver_configrules/aclsdriver_configrules.cfg.php

Whish should contain something like:
<?php
$cfg = array (
'privileges' =>
  array (
    'privilegerules' =>
    array (
      0 =>
      array (
        'users' =>
        array (
          0 => 'yourlogin',
        ),
        'is_admin' => true,
      ),
    ),
  )
)
?>

You can edit this file manually.
